<View1Layout>:
    orientation: 'vertical'
    SearchBarPanel:
        size_hint: 1, None
        height: '20mm'
        anchor_x: 'center'
        anchor_y: 'center'
    MainPanel:
    PlayBarPanel:
        size_hint: 1, None
        height: '35mm'

<SearchBarPanel>:
    TextInput:
        size_hint: None, 1
        width: '100mm'
        text: 'search bar'
        multiline: False

<PlayBarPanel>:
    Label:
        text: 'play bar'